services:
  redis:
    image: redis:7.2
    container_name: redis
    restart: "no"
    command: /bin/sh -c "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    volumes:
      - ./Redis/redis-volume:/data
    env_file:
      - ./Redis/redis.env
    ports:
      - 6379:6379
    networks:
      - spark-chat
    
  load-balancer:
    build: ./LoadBalancer
    links:
      - "redis:db"
    ports:
      - 3030:3030
    networks:
      - spark-chat

  last-seen:
    build: ./LastSeen
    depends_on:
      - redis
    links:
      - "redis:db"
    networks:
      - spark-chat
 
  sessions:
    build: ./Sessions
    depends_on:
      - redis
    links:
      - "redis:db"
    networks:
      - spark-chat

networks:
  spark-chat:
    name: spark-chat