services:
  redis:
    image: redis:7.2
    container_name: redis
    restart: "no"
    command: /bin/sh -c "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    volumes:
      - ./Redis/redis-volume:/data
    env_file:
      - ./Redis/redis.env
    ports:
      - 6379:6379
    
  load-balancer:
    build: ./LoadBalancer
    links:
      - "redis:db"
    ports:
      - 3030:3030

  last-seen:
    build: ./LastSeen
    depends_on:
      - redis
    links:
      - "redis:db"
 
  sessions:
    build: ./Sessions
    depends_on:
      - redis
    links:
      - "redis:db"