services:
  redis:
    image: redis:7.2
    container_name: redis
    restart: "no"
    command: /bin/sh -c "redis-server --appendonly yes"
    volumes:
      - ./Redis/redis-volume:/data
    ports:
      - 6379:6379
    networks:
      spark-chat:
        ipv4_address: 172.20.0.2

  websocket-server:
    build: ./Server
    ports:
      - 3000:3000
    networks:
      spark-chat:
        ipv4_address: 172.20.0.6
    command: ["node", "--prof", "index.js", "3000"]
    
  load-balancer:
    build: ./LoadBalancer
    depends_on:
      - websocket-server
    links:
      - "redis:db"
    ports:
      - 3030:3030
      - 8082:8080
    networks:
      spark-chat:
        ipv4_address: 172.20.0.3

  last-seen:
    build: ./LastSeen
    depends_on:
      - redis
      - websocket-server
    links:
      - "redis:db"
    networks:
      spark-chat:
        ipv4_address: 172.20.0.4
 
  sessions:
    build: ./Sessions
    depends_on:
      - websocket-server
      - redis
    links:
      - "redis:db"
    networks:
      spark-chat:
        ipv4_address: 172.20.0.5
  
  socket-to-queue:
    build: ./SocketToQueue
    depends_on:
      - websocket-server
      - redis
    links:
      - "redis:db"
    networks:
      spark-chat:
        ipv4_address: 172.20.0.7

networks:
  spark-chat:
    name: spark-chat
    ipam:
      config:
          - subnet: "172.20.0.0/16"
            gateway: 172.20.0.1