services:
  redis:
    image: redis:7.2
    container_name: redis
    restart: no
    command: /bin/sh -c "redis-server --appendonly yes"
    volumes:
      - ./redis-volume:/data
    ports:
      - 6379:6379